import sys
import math
from pyspark import SparkConf, SparkContext
from pyspark.sql.session import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *


class proj3:
    def run(self, inputpathA, inputpathB, outputpath, d, s):
        spark = SparkSession.builder.appName("proj3").getOrCreate()
        sc = spark.sparkContext

        d = float(d)
        s = float(s)

        # ---------- Parsing ----------
        # Each well-formed line is  record_id#(x,y)#term1 term2 ...
        def parse(line):
            rid, coord, terms = line.strip().split('#')
            x_str, y_str = coord.strip()[1:-1].split(',')
            x = float(x_str)
            y = float(y_str)
            tokens = frozenset(terms.split())
            return (rid, x, y, tokens)

        A = sc.textFile(inputpathA).filter(lambda l: len(l.strip()) > 0).map(parse)
        B = sc.textFile(inputpathB).filter(lambda l: len(l.strip()) > 0).map(parse)

        # ---------- Frequency Sorting ----------
        # Build a single global token order over BOTH datasets: rarer tokens get
        # a smaller rank (ties broken by the token string for a deterministic
        # total order). The token -> rank map is broadcast to every worker so
        # tokens can be converted to numeric ranks locally.
        token_freq = (A.union(B)
                      .flatMap(lambda r: r[3])
                      .map(lambda t: (t, 1))
                      .reduceByKey(lambda a, b: a + b)
                      .collect())
        token_freq.sort(key=lambda kv: (kv[1], kv[0]))
        rank = {tok: i for i, (tok, _) in enumerate(token_freq)}
        b_rank = sc.broadcast(rank)

        # Indexing prefix length for a Jaccard threshold s (safe / no false
        # negatives): p = |r| - ceil(s * |r|) + 1.
        def prefix_len(n):
            p = n - int(math.ceil(s * n)) + 1
            return max(1, min(p, n))

        # ---------- Prefix Filtering + Grid Index signatures ----------
        def to_signature(r):
            rid, x, y, tokens = r
            rmap = b_rank.value
            ordered = sorted(tokens, key=lambda t: rmap[t])
            prefix = ordered[:prefix_len(len(tokens))]
            cell = (int(math.floor(x / d)), int(math.floor(y / d)))
            return (rid, x, y, tokens, prefix, cell)

        A_sig = A.map(to_signature)
        B_sig = B.map(to_signature)

        # Blocking key = (prefix token, grid cell). Records from A keep their
        # home cell; records from B are replicated to their 3x3 cell
        # neighbourhood. Any A,B that share a prefix token and lie in adjacent
        # cells therefore meet on a common key.
        def emit_A(r):
            rid, x, y, tokens, prefix, (cx, cy) = r
            val = (rid, x, y, tokens)
            return [((tok, (cx, cy)), val) for tok in prefix]

        def emit_B(r):
            rid, x, y, tokens, prefix, (cx, cy) = r
            val = (rid, x, y, tokens)
            return [((tok, (cx + dx, cy + dy)), val)
                    for tok in prefix
                    for dx in (-1, 0, 1)
                    for dy in (-1, 0, 1)]

        A_keyed = A_sig.flatMap(emit_A)
        B_keyed = B_sig.flatMap(emit_B)

        # Candidate (A record, B record) pairs sharing a prefix token & cell.
        candidates = A_keyed.join(B_keyed).map(lambda kv: kv[1])

        # A pair can be generated by several keys -> de-duplicate on (A.id, B.id).
        unique_pairs = (candidates
                        .map(lambda ab: ((ab[0][0], ab[1][0]), ab))
                        .reduceByKey(lambda a, b: a)
                        .map(lambda kv: kv[1]))

        # ---------- Exact verification ----------
        def verify(ab):
            (aid, ax, ay, aset), (bid, bx, by, bset) = ab
            dist = math.sqrt((ax - bx) ** 2 + (ay - by) ** 2)
            if dist > d:
                return None
            union = len(aset | bset)
            jac = len(aset & bset) / union
            if jac < s:
                return None
            return (aid, bid, dist, jac)

        results = unique_pairs.map(verify).filter(lambda x: x is not None)

        # ---------- Ordering (by numerical id: A then B) ----------
        sorted_results = results.sortBy(lambda r: (int(r[0][1:]), int(r[1][1:])))

        output = sorted_results.map(
            lambda r: "(%s,%s):%.6f,%.6f" % (r[0], r[1], r[2], r[3]))

        output.coalesce(1).saveAsTextFile(outputpath)

        spark.stop()


if __name__ == '__main__':
    if len(sys.argv) != 6:
        print("Wrong arguments")
        sys.exit(-1)
    proj3().run(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
